<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<RootNamespace />
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<Deterministic>true</Deterministic>
		<ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
		<PublishRepositoryUrl>true</PublishRepositoryUrl>
		<EmbedUntrackedSources>true</EmbedUntrackedSources>
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<Version>1.0.0</Version>
		<GenerateDocumentationFile>True</GenerateDocumentationFile>
		<Authors>SeongSikChae</Authors>
		<Description>.NET System.Net namespace Extensions</Description>
		<RepositoryUrl>https://github.com/SeongSikChae/System.Net.Extensions.git</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<PackageProjectUrl>https://github.com/SeongSikChae/System.Net.Extensions.git</PackageProjectUrl>
		<AssemblyName>Biz.Bizadm.$(MSBuildProjectName)</AssemblyName>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageLicenseFile>LICENSE</PackageLicenseFile>
	</PropertyGroup>

	<ItemGroup>
	  <None Include="..\LICENSE">
	    <Pack>True</Pack>
	    <PackagePath>\</PackagePath>
	  </None>
	  <None Include="..\README.md">
	    <Pack>True</Pack>
	    <PackagePath>\</PackagePath>
	  </None>
	</ItemGroup>

</Project>
